application: sportsiege
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webob
  version: latest
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: latest
- name: setuptools
  version: latest


handlers:
- url: /
  script: config.routing.default

- url: /index\.html
  script: config.routing.default

- url: /css
  static_dir: static/stylesheets

- url: /js
  static_dir: static/scripts

- url: /img
  static_dir: static/images

- url: /uploads/(.*\.(gif|png|jpg))
  static_files: static/uploads/\1
  upload: static/uploads/(.*\.(gif|png|jpg))

- url: /.*
  script: config.routing.not_found